### ISSUE TITLE
Adding a dat twice deletes it

### ISSUE THREAD

**Issue by lsjroberts** [Rotonde/beaker#13]
From this commit https://github.com/Rotonde/beaker/commit/1cd703a41aa8dcdd96a034e05c3a298b245fd42c

Is this the intended behaviour? If I'm not sure if I have added someone I might enter in their dat url again. It seems it would be better to just skip it and not duplicate the entry.

Though it would be good to have a button or some other clear way to unfollow someone.

**Comment by neauoire** [comment]
Yeah, I'm working on listing all the portals on the left side bar atm, give me a few minutes and it should be resolved. I'll then make it skip the duplicates.

**Comment by neauoire** [comment]
Fixed :)
