### ISSUE TITLE
post-IDs to make threaded discussions possible?

### ISSUE THREAD

**Issue by ghost** [Rotonde/beaker#27]
i propose adding `id` to the `feed` array, which will be calculated by hash of initial message + timestamp

**Comment by lsjroberts** [comment]
I think an id would be unnecessary as we could just use the index of the message in the user's feed array. In the same way we do for the `edit:12 message` command.

But threaded discussions would definitely be cool. Or perhaps even just a `reply` button & command that makes your message link back to the original. Not necessarily like twitter's threads as those a bit of a UX nightmare.

**Comment by ghost** [comment]
as of rn entire "DB" is an array of objects. which are only stored in a text file.
- if i `delete:0` the numeration of the rest of the posts will shift by one
- if i swap two items (by editing the json file) - the thread will be corrupted

but if we have a hash generated from content itself (the very same `dat://` for example) -- you can prove the thing you replied to, has changed.

im not making a blockchain proposal here, just a better content linkage than "the second to last from the top, no the other top. the one from yesterday, remember?"

**Comment by lsjroberts** [comment]
That's a very good point. We'll look into it.

**Comment by ghost** [comment]
also, im not sure if this repo or the https://github.com/Rotonde/Specs is the one to have this issue in?

also also, there is a [`json feed`](https://jsonfeed.org/version/1) ([on github](https://github.com/brentsimmons/JSONFeed/blob/master/pages/version/1.markdown)), which is very similar to the `feed` array in `portal.json` 

except the missing `target` (reply_to) field, which could be simply added as optional extension on top of json-feed, linking to `dat://<relpied_to_hash>/<item_id>`
