### ISSUE TITLE
non-urgent feature request

### ISSUE THREAD

**Issue by LTKMN** [Rotonde/beaker#3]
@ mentions in 'tweets' (posts?) should ideally link to the profile of that person, like twitter does.

It'd be cool to follow these new people but there's no actual way of getting their profile page / dat url from merely seeing @name mentioned by someone else as plaintext.

**Comment by lsjroberts** [comment]
This commit fixes it when the message starts with the @ mention - https://github.com/Rotonde/beaker/commit/bf6cd7552f1e90a2ac949354e310c856d5ca05a1

Though it may be good to do a find-replace for any @ mention.

**Comment by neauoire** [comment]
This is working, any @ in your know network will be replaced :)
