### ISSUE TITLE
Raw dat URLs (not portal names) sometimes appear in the sidebar

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/beaker#37]
e.g. 
![screen shot 2017-10-15 at 04 56 59](https://user-images.githubusercontent.com/7245874/31584556-63e808d8-b165-11e7-84c6-f03f7c81871d.png)

**Comment by frozenpandaman** [comment]
…and sometimes this happens (zoomed out)
![image](https://user-images.githubusercontent.com/7245874/31584808-ca845038-b16a-11e7-98df-7ff37a2ba21f.png)

**Comment by lsjroberts** [comment]
The raw ones I think are when they are offline and the real name can't be retrieved.

However I have also just seen it go a little weird and flash names and raw dats in and out. I'll take a look tomorrow.

**Comment by neauoire** [comment]
I think it's because I append to the html. 
I'm sure you'll find a better way to do this.

**Comment by neauoire** [comment]
The latest version still has this issue, I can't figure it out. If someone wanna give a shot at tackling this, be my guest :)

**Comment by ianh** [comment]
I think 6f35221 fixes this.  Try updating and see if it still happens.

**Comment by frozenpandaman** [comment]
I think this is fixed. Thanks @ianh. If I find this is still a issue with the new build (separate client and user) I'll reopen another issue over at https://github.com/Rotonde/rotonde-client.
