### ISSUE TITLE
Git Still Tracks Files in the .gitignore

### ISSUE THREAD

**Issue by Capital-EX** [Rotonde/beaker#38]
I've notice that git is still tracking the changes made for files listed in the .gitignore.  Since `dat.json`, `portal.json`, `links/custom.css`, `media/content/icon.svg` have previously been committed to the repo their change will continue to be tracked.

The fallowing command will cause those files to be 'forgotten' without removing them:
`git update-index --assume-unchanged links/custom.css media/content/icon.svg dat.json portal.json`

[stackover source](https://stackoverflow.com/a/6380221)

**Comment by cblgh** [comment]
ah yes, i wrote that in a [commit comment](https://github.com/Rotonde/beaker/commit/ce191092c06f428eb9681091f6bbc6b5c229d2d4) but it should probably be made more prominent, thanks!
