### ISSUE TITLE
createFileActivityStream is called way more than needed

### ISSUE THREAD

**Issue by pfrazee** [Rotonde/beaker#55]
I was debugging why Beaker was telling me about too many event emitters registered when I visit Rotonde. We may have a leak, but I found that `createFileActivityStream` is being run more than once (much much more than once) for each feed. It should only ever happen one time per feed, and then you should hold on to that reference.

https://github.com/Rotonde/beaker/blob/6590f0f2671db90033d09c8170e3dc3f17499585/scripts/feed.js#L79

**Comment by neauoire** [comment]
Oh, yeah I re-set it on every refresh. I will fix that up!

**Comment by neauoire** [comment]
Fixed in https://github.com/Rotonde/beaker/commit/38e6e120ef1257bd64eb442f08fa1da3766d5e03

**Comment by pfrazee** [comment]
👍
