### ISSUE TITLE
This feed does not load and blocks the feed list

### ISSUE THREAD

**Issue by lsjroberts** [Rotonde/beaker#7]
dat://rotonde-edouard.hashbase.io/

When I visit it I just get a blank page and no errors in the console.

<img width="814" alt="screen shot 2017-10-13 at 20 23 06" src="https://user-images.githubusercontent.com/3817697/31560387-6130bc64-b054-11e7-900a-e47411709cfa.png">

And if I have this in my `portal.json` the whole feed list does not render.

**Comment by neauoire** [comment]
Yeah, people shouldn't share their hashbase URLs, I don't understand why people don't give out their actual hash instead.. Don't add hashbase to your portals, ask the person their actual hash instead.

**Comment by pfrazee** [comment]
Hashbase URLs (or any url with a shortname) should work just fine, right?

**Comment by neauoire** [comment]
Well, hashbase has been really slow, for one thing. Also, if we really want to be decentralized, I would prefer people to start building peer networks instead of relying on hashbase hosting.

**Comment by pfrazee** [comment]
That's fair. (And yeah it's not as fast as it should be.)

**Comment by lsjroberts** [comment]
That makes sense. Though just in case it is not related to hashbase, it is worth noting other hashbase ones I follow do load correctly.

**Comment by neauoire** [comment]
@pfrazee Is there a way to check if you own/have writing access on a site?

**Comment by pfrazee** [comment]
@neauoire yeah getInfo() should include `isOwner` in its response. https://beakerbrowser.com/docs/apis/dat.html#getinfo

**Comment by neauoire** [comment]
Perfect! I missed that part. Works beautifully.

**Comment by lsjroberts** [comment]
The block this causes is fixed by #11, but the underlying issue still remains.

**Comment by neauoire** [comment]
I think we could close this one.

**Comment by lsjroberts** [comment]
Yep both the causes are fixed I believe.

**Comment by lsjroberts** [comment]
Well, I mean an invalid portal.json will cause this still but we can open a new issue to chat error messages and things later.
