### ISSUE TITLE
Load the feeds in parallel

### ISSUE THREAD

**Issue by lsjroberts** [Rotonde/beaker#8]
Rather than having the feeds load serially and block on each feed (https://github.com/Rotonde/beaker/blob/master/scripts/feed.js#L44), it might be a nicer experience to instead have them run in parallel.

As each feed resolves merge it into the list. It might require a bit of subtle animation as items are inserted to avoid content jumping too much. Or perhaps if a new one loads after the first 3 seconds insert it as a collapsed item which can be expanded.

Some extra feedback on the left panel with something like "8 of 14 feeds loaded" would be nice. Along with "2 feeds offline" etc.

I'm happy to take this on if this sounds like a good idea to you :)

**Comment by neauoire** [comment]
That's what I would like, but I don't know how :) 
I would be really happy if you could handle it, if only so I can learn from it. 
cheers!

**Comment by lsjroberts** [comment]
Sure thing!
