### ISSUE TITLE
Putting my dat url in the input duplicates all posts

### ISSUE THREAD

**Issue by tttimur** [Rotonde/beaker#9]
I was attempting to put a dat url into the input but it doubled all my posts. Even if I delete them, all future posts are doubled. 

reference: dat://a947b0c0ba330763257208f14f40b0779b0dfc4bcf0fa4a49232abc6326b9326/

As you can see it says there are 4 entries, however there are currently 8.

**Comment by neauoire** [comment]
Haha, yeah I've had that happen to me. I'll fix this now, can you just edit portal.json and remove yourself from the port=[] array :)? I'll get on that right away.

**Comment by tttimur** [comment]
okay! 

thanks

**Comment by neauoire** [comment]
Fixed :) Pull the latest version(keep your portal.json somewhere), and that problem should be gone!
